# -*- coding: utf-8 -*-
"""breast canser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpgSdcK10_ZHRio7mbv3iQMuA6vFYnVj

# Making the Most of your Colab Subscription
"""

import numpy as np
import pandas as pd

breast = pd.read_csv('data.csv')

breast.head()

breast['diagnosis'].value_counts()

breast.shape

breast.isnull().sum()

breast.duplicated().sum()

breast.info()

breast.select_dtypes(include=np.number).corr()

breast.describe()

# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# breast['diagnosis'] = le.fit_transform(breast['diagnosis'])

breast['diagnosis'] = breast['diagnosis'].map({'M':1,'B':0})

breast['diagnosis'].value_counts()

x =breast.drop('diagnosis',axis=1)
y= breast['diagnosis']

x.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

x_test.shape

x_train

from sklearn.preprocessing import StandardScaler
sc  = StandardScaler()

sc.fit(x_train)

x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

x_train

from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

lg.fit(x_train,y_train)
y_pred = lg.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

y_pred

input_text = (1.97409619,  1.73302577,  2.09167167,  1.85197292,  1.319843  ,
        3.42627493,  2.01311199,  2.66503199,  2.1270036 ,  1.55839569,
        0.80531919, -0.81268678,  0.75195659,  0.87716951, -0.89605315,
        1.18122247,  0.18362761,  0.60059598, -0.31771686,  0.52963649,
        2.17331385,  1.3112795 ,  2.08161691,  2.1374055 ,  0.76192793,
        3.26560084,  1.92862053,  2.6989469 ,  1.89116053,  2.49783848)
np_df = np.asarray(input_text)
prediciont = lg.predict(np_df.reshape(1,-1))

if prediciont[0]==1:
  print("cancrous")
else:
  print("not cancrous")

x_train[1]

x_train[10]

import pickle
pickle.dump(lg,open('model.pkl','wb'))

